# Generated by Django 2.0.6 on 2018-12-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aprendiz',
            name='apellido',
        ),
    ]
