# Generated by Django 2.0.7 on 2018-12-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_aprendiz_apellido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega_material',
            name='fecha_ingresa',
            field=models.DateField(default='2018-12-12'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(default='2018-12-12'),
        ),
    ]
